version: '3'

services:
  nas-nav:
    container_name: nas-nav
    build: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
